# fly.toml app configuration file generated for bklt-q on 2023-08-29T13:36:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bklt-q"
primary_region = "ewr"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "redis_server"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics"
